// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgxorXkpIFPLVm0YLrexyBTbIP8NQJ0CI',
    appId: '1:145330881660:web:6b2627b56e69c1468e75f9',
    messagingSenderId: '145330881660',
    projectId: 'bookbus-cantho',
    authDomain: 'bookbus-cantho.firebaseapp.com',
    storageBucket: 'bookbus-cantho.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANrTVByFMa3LBRHyUGH9nrnvm-cf9wG-E',
    appId: '1:145330881660:android:151d56ae27e25faa8e75f9',
    messagingSenderId: '145330881660',
    projectId: 'bookbus-cantho',
    storageBucket: 'bookbus-cantho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC24KfyCrqKQrWdSlXwJlghW3hNHeX6ck',
    appId: '1:145330881660:ios:df7ce1c7d191de2d8e75f9',
    messagingSenderId: '145330881660',
    projectId: 'bookbus-cantho',
    storageBucket: 'bookbus-cantho.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgxorXkpIFPLVm0YLrexyBTbIP8NQJ0CI',
    appId: '1:145330881660:web:16fa783be1ac9aa68e75f9',
    messagingSenderId: '145330881660',
    projectId: 'bookbus-cantho',
    authDomain: 'bookbus-cantho.firebaseapp.com',
    storageBucket: 'bookbus-cantho.firebasestorage.app',
  );
}
